### ISSUE TITLE
Define more dimension names

### ISSUE THREAD

**Issue by propensive** [propensive/quantitative#26]
The list at https://en.wikipedia.org/wiki/List_of_physical_quantities is part-way through being converted into code in `src/core/quantify.scala`, but still has a lot of quantities missing.

**Comment by sha0urya** [comment]
Sir, i want to work on this issue. It would be really great if you assign me.

Thank you..!!

**Comment by propensive** [comment]
This has worked out to be quite bad timing... I actually finished implementing the list only yesterday, but I was slow to close this issue. Sorry, @sha0urya.

If there are any other issues in Quantitative you'd like to work on, please let me know and I'll be happy to facilitate in any way I can!

**Comment by sha0urya** [comment]
Ok sir, No worries..
Thank you sir.. 
I will looking to find some other issues in your repo.
